name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}
author: games647
version: ${project.version}
description: ${project.description}
website: ${project.url}
database: true
softdepend: [mcMMO, Vault, SimpleClans, InSigns, Essentials, Factions, Jobs]
commands:
  sbs:
    usage: /sbs
permissions:
  scoreboardstats.use:
    default: true